[project]
name = "capture-flag-tests"
version = "0.1.0"
dependencies = [
    "playwright",
    "pytest",
    "pytest-asyncio",
    "requests",
    "pillow",
    "fastmcp",
    "websockets",
    "dotenv",
    "google-genai",
    "anthropic",
    "pydantic-ai"
]